package ru.otvykaniye.tracker.ui.theme

object Strings {
    val RU = mapOf(
        "time_passed" to "С последнего использования прошло",
        "record" to "Записать",
        "craving_sos" to "Тяга SOS",
        "target" to "ЦЕЛЬ",
        "health" to "ЗДОРОВЬЕ",
        "stats" to "СТАТИСТИКА",
        "history" to "ИСТОРИЯ",
        "today" to "Сегодня",
        "limit" to "Лимит",
        "no_entries" to "Пока нет записей",
        "stage_0" to "Начальный этап",
        "stage_0_desc" to "Давление и пульс приходят в норму.",
        "stage_1" to "Очищение крови",
        "stage_1_desc" to "Уровень угарного газа падает до нормы.",
        "stage_2" to "Снижение рисков",
        "stage_2_desc" to "Риск инфаркта начинает снижаться.",
        "stage_3" to "Вывод никотина",
        "stage_3_desc" to "Никотин полностью выведен из организма.",
        "stage_4" to "Глубокое восстановление",
        "stage_4_desc" to "Функция легких значительно улучшается.",
        "next_stage" to "Далее: %s",
        "chart_14_days" to "ГРАФИК 14 ДНЕЙ",
        "tap_bar" to "Нажми на столбик",
        "pcs" to "шт",
        "time_of_use" to "ВРЕМЯ УПОТРЕБЛЕНИЯ",
        "morning" to "Утро",
        "day" to "День",
        "evening" to "Вечер",
        "night" to "Ночь",
        "settings" to "Настройки",
        "save" to "Сохранить",
        "tracker_limits" to "ТРЕКЕР И ЛИМИТЫ",
        "daily_limit_pcs" to "Дневной лимит (шт)",
        "nicotine_calculation" to "НИКОТИН",
        "nic_format" to "Формат на упаковке",
        "nic_per_pouch" to "В 1 шт",
        "nic_per_pack" to "В целой пачке",
        "nic_per_gram" to "На 1 грамм",
        "nicotine_amount" to "Заявленный никотин (мг)",
        "pouch_weight" to "Вес 1 шт (г)",
        "wishlist" to "ЦЕЛЬ (ЖЕЛАННОЕ)",
        "wishlist_title" to "Название цели",
        "wishlist_cost" to "Стоимость",
        "savings" to "СЭКОНОМЛЕНО",
        "baseline_per_day" to "Штук в день до (в среднем)",
        "price_per_pack" to "Цена за пачку",
        "pcs_per_pack" to "Штук в пачке",
        "sos_title" to "Справиться с тягой",
        "sos_desc" to "Острая тяга длится 3-5 минут. Дышите.",
        "sos_inhale" to "ВДОХ",
        "sos_hold" to "ЗАДЕРЖКА",
        "sos_exhale" to "ВЫДОХ",
        "sos_remains" to "Осталось переждать:",
        "sos_success" to "Тяга преодолена!",
        "snus" to "Снюс",
        "cigarettes" to "Сигареты",
        "data_management" to "УПРАВЛЕНИЕ ДАННЫМИ",
        "export_backup" to "Экспорт (Бэкап)",
        "import_backup" to "Импорт (Восстановить)",
        "reset_data" to "Сбросить все данные"
    )

    val EN = mapOf(
        "time_passed" to "Time since last use",
        "record" to "Record",
        "craving_sos" to "Craving SOS",
        "target" to "TARGET",
        "health" to "HEALTH",
        "stats" to "STATISTICS",
        "history" to "HISTORY",
        "today" to "Today",
        "limit" to "Limit",
        "no_entries" to "No entries yet",
        "stage_0" to "Initial phase",
        "stage_0_desc" to "Blood pressure and heart rate returning to normal.",
        "stage_1" to "Blood clearing",
        "stage_1_desc" to "Carbon monoxide levels drop to normal.",
        "stage_2" to "Risk reduction",
        "stage_2_desc" to "Heart attack risk begins to decrease.",
        "stage_3" to "Nicotine cleared",
        "stage_3_desc" to "Nicotine is completely out of your body.",
        "stage_4" to "Deep recovery",
        "stage_4_desc" to "Lung function improves.",
        "next_stage" to "Next: %s",
        "chart_14_days" to "14-DAY CHART",
        "tap_bar" to "Tap a bar",
        "pcs" to "pcs",
        "time_of_use" to "TIME OF USE",
        "morning" to "Morning",
        "day" to "Day",
        "evening" to "Evening",
        "night" to "Night",
        "settings" to "Settings",
        "save" to "Save",
        "tracker_limits" to "TRACKER & LIMITS",
        "daily_limit_pcs" to "Daily limit (pcs)",
        "nicotine_calculation" to "NICOTINE",
        "nic_format" to "Format on packaging",
        "nic_per_pouch" to "Per pouch",
        "nic_per_pack" to "Per entire pack",
        "nic_per_gram" to "Per 1 gram",
        "nicotine_amount" to "Declared nicotine (mg)",
        "pouch_weight" to "1 pouch weight (g)",
        "wishlist" to "WISHLIST",
        "wishlist_title" to "Target name",
        "wishlist_cost" to "Target cost",
        "savings" to "SAVINGS",
        "baseline_per_day" to "Used per day before",
        "price_per_pack" to "Price per pack",
        "pcs_per_pack" to "Pieces in pack",
        "sos_title" to "Overcome craving",
        "sos_desc" to "Acute cravings last 3-5 minutes. Breathe.",
        "sos_inhale" to "INHALE",
        "sos_hold" to "HOLD",
        "sos_exhale" to "EXHALE",
        "sos_remains" to "Time remaining:",
        "sos_success" to "Craving is gone!",
        "snus" to "Snus",
        "cigarettes" to "Cigarettes",
        "data_management" to "DATA MANAGEMENT",
        "export_backup" to "Export Backup",
        "import_backup" to "Import Backup",
        "reset_data" to "Reset All Data"
    )

    fun get(lang: String, key: String): String {
        return if (lang == "en") EN[key] ?: key else RU[key] ?: key
    }
}